chmod +x scripts/ccp.sh
chmod +x scripts/createAppChannel.sh
chmod +x scripts/createChannel.sh
chmod +x scripts/createGenesis.sh
chmod +x scripts/orderer-certs.sh
chmod +x scripts/org1-certs.sh
chmod +x scripts/org2-certs.sh
chmod +x scripts/org3-certs.sh
chmod +x scripts/updateAnchorPeer.sh
